Adding CI/CD workflow (#1)

diff --git a/aws-ecs-github-runner-nginx/Dockerfile b/aws-ecs-github-runner-nginx/Dockerfile
--- a/aws-ecs-github-runner-nginx/Dockerfile
+++ b/aws-ecs-github-runner-nginx/Dockerfile
@@ -1,13 +1,17 @@
 ARG OPENRESTY_INSTALL_FOLDER='/usr/local/openresty'
+ARG ALPINE_VERSION=3.21.3
 
 # Build OpenResty with ngx_http_proxy_connect_module
-FROM alpine:latest AS builder
+FROM alpine:${ALPINE_VERSION} AS builder
 
 ARG NGINX_VERSION=1.25.3
 ARG OPENRESTY_VERSION=${NGINX_VERSION}.2
 ARG MODULE_PATCH=102101
 ARG OPENRESTY_INSTALL_FOLDER
 ENV OPENRESTY_INSTALL_FOLDER=${OPENRESTY_INSTALL_FOLDER}
+
+# Prevent silent failures in pipes
+SHELL ["/bin/ash", "-o", "pipefail", "-c"]
 
 RUN apk add --no-cache \
     build-base \
@@ -23,7 +27,7 @@ RUN apk add --no-cache \
 WORKDIR /app
 
 # Download OpenResty source
-RUN wget https://openresty.org/download/openresty-${OPENRESTY_VERSION}.tar.gz && \
+RUN wget --progress=dot:giga https://openresty.org/download/openresty-${OPENRESTY_VERSION}.tar.gz && \
     tar -xvzf openresty-${OPENRESTY_VERSION}.tar.gz
 
 # Clone the proxy_connect module
@@ -44,38 +48,53 @@ RUN ./configure \
     --with-luajit \
     --add-module=../ngx_http_proxy_connect_module && \
     patch -d build/nginx-${NGINX_VERSION} -p 1 < ../ngx_http_proxy_connect_module/patch/proxy_connect_rewrite_${MODULE_PATCH}.patch && \
-    make -j$(nproc) && make install
+    make -j"$(nproc)" && make install
+
+WORKDIR /app
+
+# RUN rm -rf openresty-${OPENRESTY_VERSION} openresty-${OPENRESTY_VERSION}.tar.gz ngx_http_proxy_connect_module
 
 RUN mkdir -p /opt/deps && \
     ldd ${OPENRESTY_INSTALL_FOLDER}/nginx/sbin/nginx | awk '{print $3}' | grep "^/" | xargs -I '{}' cp -v '{}' /opt/deps/
 
-RUN cp -r ${OPENRESTY_INSTALL_FOLDER}/luajit /opt/luajit
+# RUN cp -r ${OPENRESTY_INSTALL_FOLDER}/luajit /opt/luajit
 
 # Final lightweight Alpine image
-FROM alpine:latest
+FROM alpine:${ALPINE_VERSION}
 
 ARG OPENRESTY_INSTALL_FOLDER
 ENV OPENRESTY_INSTALL_FOLDER=${OPENRESTY_INSTALL_FOLDER}
 
+# Prevent silent failures in pipes
+SHELL ["/bin/ash", "-o", "pipefail", "-c"]
+
 RUN apk add --no-cache \
-    ca-certificates \
-    pcre \
-    openssl \
-    zlib \
-    curl
-
-COPY --from=builder ${OPENRESTY_INSTALL_FOLDER} /usr/local/openresty
-
+        ca-certificates \
+        pcre \
+        openssl \
+        zlib \
+        curl \
+        python3 \
+        py3-pip \
+        py3-jinja2 \
+    rm -rf /lib/apk/db /etc/apk /var/cache/apk/*
+    
 # Copy required shared libraries
+COPY --from=builder ${OPENRESTY_INSTALL_FOLDER} ${OPENRESTY_INSTALL_FOLDER}
+# COPY --from=builder /opt/luajit ${OPENRESTY_INSTALL_FOLDER}/luajit
 COPY --from=builder /opt/deps/* /lib/
-COPY --from=builder /opt/luajit /usr/local/openresty/luajit
 
-ENV PATH="/usr/local/openresty/bin:/usr/local/openresty/nginx/sbin:$PATH"
-ENV LD_LIBRARY_PATH="/lib:/usr/local/openresty/luajit/lib"
+ENV PATH="${OPENRESTY_INSTALL_FOLDER}/bin:${OPENRESTY_INSTALL_FOLDER}/nginx/sbin:$PATH"
+ENV LD_LIBRARY_PATH="/lib:${OPENRESTY_INSTALL_FOLDER}/luajit/lib"
+
+WORKDIR /app
 
 # Copy custom OpenResty configuration
-COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
+COPY nginx.conf templates/nginx.conf
+COPY entrypoint.py entrypoint.py
+
+RUN chmod +x entrypoint.py
 
 EXPOSE 3128
 
-ENTRYPOINT  ["/bin/sh", "-c", "nginx -g 'daemon off;'"]
+ENTRYPOINT  ["./entrypoint.py", "--template-dir", "templates", "--template-file", "nginx.conf", "--output-file", "/usr/local/openresty/nginx/conf/nginx.conf" ]
diff --git a/aws-ecs-github-runner/Dockerfile b/aws-ecs-github-runner/Dockerfile
--- a/aws-ecs-github-runner/Dockerfile
+++ b/aws-ecs-github-runner/Dockerfile
@@ -1,25 +1,26 @@
 FROM ubuntu:22.04
 
-ARG RUNNER_VERSION=2.320.0
+ARG RUNNER_VERSION=2.322.0
+
+# Prevent silent failures in pipes
+SHELL ["/bin/bash", "-o", "pipefail", "-c"] 
 
 RUN apt-get update && \
-    apt-get install -y \
-        curl \
+    apt-get install --no-install-recommends -y \
         ca-certificates \
+        curl \
         wget \
         unzip \
         git \
-        cron \
         supervisor \
         jq \
         sudo \
-        libicu-dev \
     && rm -rf /var/lib/apt/lists/*
-    # && git lfs install
         
 RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
     unzip awscliv2.zip && \
-    sudo ./aws/install
+    ./aws/install && \
+    rm -rf awscliv2.zip ./aws
 
 RUN useradd -m -s /bin/bash runner && \
     echo "runner ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
@@ -30,18 +31,17 @@ WORKDIR ${HOME}
 
 USER runner
 
-RUN mkdir actions-runner && cd actions-runner && \
-    # Download the latest runner package
-    curl -o actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz -L https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz && \
-    # Optional: Validate the hash
-    echo "93ac1b7ce743ee85b5d386f5c1787385ef07b3d7c728ff66ce0d3813d5f46900  actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz" | shasum -a 256 -c && \
-    # Extract the installer
+WORKDIR ${HOME}/actions-runner
+# mkdir actions-runner && cd actions-runner && \
+# Download the latest runner package
+RUN curl -o actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz -L https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz && \
+    echo "b13b784808359f31bc79b08a191f5f83757852957dd8fe3dbfcc38202ccf5768  actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz" | shasum -a 256 -c && \
     tar xzf ./actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz
 
 USER root
 
-RUN ln -s ${PWD}/actions-runner/config.sh /bin/github-runner-config && \
-    ln -s ${PWD}/actions-runner/run.sh /bin/github-runner-run
+RUN ln -s "${PWD}/actions-runner/config.sh" "/bin/github-runner-config" && \
+    ln -s "${PWD}/actions-runner/run.sh" "/bin/github-runner-run"
 
 USER runner
 
